{% set name = "lightning-utilities" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lightning-utilities-{{ version }}.tar.gz
  sha256: 9748a5466490d6e45c2df60c1ee77ff37a1a660ea6313bc0832ab7317a081cef

build:
  number: 1
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - importlib-metadata >=4.0.0  # [py<38]
    - packaging >=17.1
    - typing_extensions

test:
  imports:
    - lightning_utilities
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Common Python utilities and GitHub Actions in Lightning Ecosystem.
  dev_url: https://github.com/Lightning-AI/utilities
  doc_url: https://github.com/Lightning-AI/utilities

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
  skip-lints:
    - python_build_tool_in_run
