{% set name = "lightning-utilities" %}
{% set version = "0.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lightning-AI/{{ name.split('-')[1] }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ca2206a5f6137fd53072081407fab2a870590fa1d34bb03b4d4faf99f32b439b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  skip: True  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - importlib-metadata >=4.0.0  # [py<38]
    - packaging >=17.1
    - typing_extensions

test:
  source_files:
    - tests/unittests
  imports:
    - lightning_utilities
  commands:
    - pip check
    - pytest -v tests/unittests/core
  requires:
    - pip
    - pytest >=8.4.*
    - requests >=2.0.0

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Common Python utilities and GitHub Actions in Lightning Ecosystem.
  dev_url: https://github.com/Lightning-AI/utilities
  doc_url: https://dev-toolbox.rtfd.io

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
  skip-lints:
    - python_build_tool_in_run
