{% set name = "lightning-utilities" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Lightning-AI/{{ name.split('-')[1] }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0ade0cbb1c06921166bdd136c7a810ee3c16a1784de6855d8f39af1b6505add7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - packaging >=22
    - typing_extensions

test:
  source_files:
    - tests/unittests
  imports:
    - lightning_utilities
  commands:
    - pip check
    - pytest -v tests/unittests/core
  requires:
    - pip
    - pytest >=9
    - requests >=2.0.0

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Common Python utilities and GitHub Actions in Lightning Ecosystem.
  dev_url: https://github.com/Lightning-AI/utilities
  doc_url: https://dev-toolbox.readthedocs.io

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
  skip-lints:
    - python_build_tool_in_run
