{% set name = "lightning-utilities" %}
{% set version = "0.11.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-','_') }}-{{ version }}.tar.gz
  sha256: f5052b81344cc2684aa9afd74b7ce8819a8f49a858184ec04548a5a109dfd053

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - importlib-metadata >=4.0.0  # [py<38]
    - packaging >=17.1
    - typing_extensions

test:
  imports:
    - lightning_utilities
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Lightning-AI/utilities
  summary: PyTorch Lightning Sample project.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    Common Python utilities and GitHub Actions in Lightning Ecosystem.
  dev_url: https://github.com/Lightning-AI/utilities
  doc_url: https://github.com/Lightning-AI/utilities

extra:
  recipe-maintainers:
    - Borda
    - carmocca
    - Tobias-Fischer
  skip-lints:
    - python_build_tool_in_run
